In [5]:
import numpy as np
rotate_x=np.array([
    [1, 0, 0],
    [0, 0, -1],
    [0, 1, 0]
    ])

rotate_y=np.array([
    [ 0,  0, 1],
    [ 0,  1,  0],
    [ -1,  0,  0]
])

rotate_z=np.array([
    [0, -1, 0],
    [1, 0, 0],
    [0, 0, 1]
])

print(np.transpose(rotate_z))

[[ 0  1  0]
 [-1  0  0]
 [ 0  0  1]]
